### ISSUE TITLE
Unable to start on MacOS

### ISSUE THREAD

**Issue by fai-9** [BinaryAlley/DatasetTag#2] opened 2024-01-10 23:39 UTC
An error occurred when running on MacOS.

- Mac mini 2023
    - Apple M2
    - Ventura 13.6.1

```
$ dotnet DatasetTag.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DatasetTag.MainWindow.HandleWindowStateChanged(WindowState state) in A:\work\DatasetTag\src\DatasetTag\MainWindow.axaml.cs:line 1261
   at Avalonia.Native.WindowImpl.WindowEvents.Avalonia.Native.Interop.IAvnWindowEvents.WindowStateChanged(AvnWindowState state) in /_/src/Avalonia.Native/WindowImpl.cs:line 63
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowEventsVTable.WindowStateChanged(Void* this, AvnWindowState state) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4248
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 59
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at DatasetTag.Program.Main(String[] args) in A:\work\DatasetTag\src\DatasetTag\Program.cs:line 12
zsh: abort      dotnet DatasetTag.dll
```

**Comment by BinaryAlley** [comment] 2024-01-11 09:13
Hello, thanks for reporting this!
Duplicate of #1

**Comment by BinaryAlley** [comment] 2024-01-15 09:16
Closing this as it's a duplicate of #1, which has been resolved.

**Closed as completed by BinaryAlley** 2024-01-15 09:16 UTC
Labels: bug
